title: Martin Marquez
# logo
description: Sr. Web Engineer
show_downloads: true
#theme: minima
remote_theme: jekyll/minima@1e8a445

url: "https://my_domain.com"
disqus:
  shortname: my_disqus_shortname

author:
  name: John Smith
  email: "john.smith@foobar.com"

minima:
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
  show_excerpts: true
  hide_site_feed_link: true  # `false` or `null` by default

# google_analytics: G-NNNNNNNNNN  // The former `UA-NNNNNNNN-N` format is no longer supported by Google
